//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/AbstractTypeStringConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AbstractTypeStringConverter")
#ifdef RESTRICT_AbstractTypeStringConverter
#define INCLUDE_ALL_AbstractTypeStringConverter 0
#else
#define INCLUDE_ALL_AbstractTypeStringConverter 1
#endif
#undef RESTRICT_AbstractTypeStringConverter

#if !defined (OrgJodaConvertAbstractTypeStringConverter_) && (INCLUDE_ALL_AbstractTypeStringConverter || defined(INCLUDE_OrgJodaConvertAbstractTypeStringConverter))
#define OrgJodaConvertAbstractTypeStringConverter_

@protocol JavaLangReflectType;

@interface OrgJodaConvertAbstractTypeStringConverter : NSObject

#pragma mark Package-Private

- (instancetype)init;

+ (id<JavaLangReflectType>)parseWithNSString:(NSString *)str;

@end

J2OBJC_STATIC_INIT(OrgJodaConvertAbstractTypeStringConverter)

FOUNDATION_EXPORT void OrgJodaConvertAbstractTypeStringConverter_init(OrgJodaConvertAbstractTypeStringConverter *self);

FOUNDATION_EXPORT id<JavaLangReflectType> OrgJodaConvertAbstractTypeStringConverter_parseWithNSString_(NSString *str);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertAbstractTypeStringConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_AbstractTypeStringConverter")
