//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/AnnotationStringConverterFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AnnotationStringConverterFactory")
#ifdef RESTRICT_AnnotationStringConverterFactory
#define INCLUDE_ALL_AnnotationStringConverterFactory 0
#else
#define INCLUDE_ALL_AnnotationStringConverterFactory 1
#endif
#undef RESTRICT_AnnotationStringConverterFactory

#if !defined (OrgJodaConvertAnnotationStringConverterFactory_) && (INCLUDE_ALL_AnnotationStringConverterFactory || defined(INCLUDE_OrgJodaConvertAnnotationStringConverterFactory))
#define OrgJodaConvertAnnotationStringConverterFactory_

#define RESTRICT_StringConverterFactory 1
#define INCLUDE_OrgJodaConvertStringConverterFactory 1
#include "StringConverterFactory.h"

@class IOSClass;
@protocol OrgJodaConvertStringConverter;

@interface OrgJodaConvertAnnotationStringConverterFactory : NSObject < OrgJodaConvertStringConverterFactory >

#pragma mark Public

- (id<OrgJodaConvertStringConverter>)findConverterWithIOSClass:(IOSClass *)cls;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(OrgJodaConvertAnnotationStringConverterFactory)

inline id<OrgJodaConvertStringConverterFactory> OrgJodaConvertAnnotationStringConverterFactory_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<OrgJodaConvertStringConverterFactory> OrgJodaConvertAnnotationStringConverterFactory_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJodaConvertAnnotationStringConverterFactory, INSTANCE, id<OrgJodaConvertStringConverterFactory>)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertAnnotationStringConverterFactory)

#endif

#pragma pop_macro("INCLUDE_ALL_AnnotationStringConverterFactory")
