//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/factory/ByteObjectArrayStringConverterFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ByteObjectArrayStringConverterFactory")
#ifdef RESTRICT_ByteObjectArrayStringConverterFactory
#define INCLUDE_ALL_ByteObjectArrayStringConverterFactory 0
#else
#define INCLUDE_ALL_ByteObjectArrayStringConverterFactory 1
#endif
#undef RESTRICT_ByteObjectArrayStringConverterFactory

#if !defined (OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_) && (INCLUDE_ALL_ByteObjectArrayStringConverterFactory || defined(INCLUDE_OrgJodaConvertFactoryByteObjectArrayStringConverterFactory))
#define OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_

#define RESTRICT_StringConverterFactory 1
#define INCLUDE_OrgJodaConvertStringConverterFactory 1
#include "StringConverterFactory.h"

@class IOSClass;
@protocol OrgJodaConvertStringConverter;

@interface OrgJodaConvertFactoryByteObjectArrayStringConverterFactory : NSObject < OrgJodaConvertStringConverterFactory >

#pragma mark Public

- (id<OrgJodaConvertStringConverter>)findConverterWithIOSClass:(IOSClass *)cls;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(OrgJodaConvertFactoryByteObjectArrayStringConverterFactory)

inline id<OrgJodaConvertStringConverterFactory> OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<OrgJodaConvertStringConverterFactory> OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJodaConvertFactoryByteObjectArrayStringConverterFactory, INSTANCE, id<OrgJodaConvertStringConverterFactory>)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertFactoryByteObjectArrayStringConverterFactory)

#endif

#if !defined (OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter_) && (INCLUDE_ALL_ByteObjectArrayStringConverterFactory || defined(INCLUDE_OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter))
#define OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_TypedStringConverter 1
#define INCLUDE_OrgJodaConvertTypedStringConverter 1
#include "TypedStringConverter.h"

@class IOSClass;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter_Enum) {
  OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter_Enum_INSTANCE = 0,
};

@interface OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter : JavaLangEnum < NSCopying, OrgJodaConvertTypedStringConverter >

#pragma mark Public

- (IOSObjectArray *)convertFromStringWithIOSClass:(IOSClass *)arg0
                                     withNSString:(NSString *)arg1;

+ (OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter *OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter_values_[];

inline OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter *OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter_get_INSTANCE();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter, INSTANCE)

FOUNDATION_EXPORT IOSObjectArray *OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter_values();

FOUNDATION_EXPORT OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter *OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter *OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertFactoryByteObjectArrayStringConverterFactory_ByteArrayStringConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_ByteObjectArrayStringConverterFactory")
