//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/FromStringConverter.java
//

#include "FromStringConverter.h"
#include "J2ObjC_source.h"

@interface OrgJodaConvertFromStringConverter : NSObject

@end

@implementation OrgJodaConvertFromStringConverter

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSObject;", 0x401, 0, 1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(convertFromStringWithIOSClass:withNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "convertFromString", "LIOSClass;LNSString;", "(Ljava/lang/Class<+TT;>;Ljava/lang/String;)TT;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _OrgJodaConvertFromStringConverter = { "FromStringConverter", "org.joda.convert", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, 3, -1 };
  return &_OrgJodaConvertFromStringConverter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJodaConvertFromStringConverter)
