//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/FromString.java
//

#include "FromString.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

__attribute__((unused)) static IOSObjectArray *OrgJodaConvertFromString__Annotations$0();

@implementation OrgJodaConvertFromString

- (IOSClass *)annotationType {
  return OrgJodaConvertFromString_class_();
}

- (NSString *)description {
  return @"@org.joda.convert.FromString()";
}

+ (const J2ObjcClassInfo *)__metadata {
  static const void *ptrTable[] = { (void *)&OrgJodaConvertFromString__Annotations$0 };
  static const J2ObjcClassInfo _OrgJodaConvertFromString = { "FromString", "org.joda.convert", ptrTable, NULL, NULL, 7, 0x2609, 0, 0, -1, -1, -1, -1, 0 };
  return &_OrgJodaConvertFromString;
}

@end

id<OrgJodaConvertFromString> create_OrgJodaConvertFromString() {
  OrgJodaConvertFromString *self = AUTORELEASE([[OrgJodaConvertFromString alloc] init]);
  return self;
}

IOSObjectArray *OrgJodaConvertFromString__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangAnnotationTarget([IOSObjectArray newArrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, METHOD), JreLoadEnum(JavaLangAnnotationElementType, CONSTRUCTOR) } count:2 type:NSObject_class_()]), create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, RUNTIME)) } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJodaConvertFromString)
