//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/FromStringConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_FromStringConverter")
#ifdef RESTRICT_FromStringConverter
#define INCLUDE_ALL_FromStringConverter 0
#else
#define INCLUDE_ALL_FromStringConverter 1
#endif
#undef RESTRICT_FromStringConverter

#if !defined (OrgJodaConvertFromStringConverter_) && (INCLUDE_ALL_FromStringConverter || defined(INCLUDE_OrgJodaConvertFromStringConverter))
#define OrgJodaConvertFromStringConverter_

@class IOSClass;

@protocol OrgJodaConvertFromStringConverter < JavaObject >

- (id)convertFromStringWithIOSClass:(IOSClass *)cls
                       withNSString:(NSString *)str;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaConvertFromStringConverter)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertFromStringConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_FromStringConverter")
