//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/FromString.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_FromString")
#ifdef RESTRICT_FromString
#define INCLUDE_ALL_FromString 0
#else
#define INCLUDE_ALL_FromString 1
#endif
#undef RESTRICT_FromString

#if !defined (OrgJodaConvertFromString_) && (INCLUDE_ALL_FromString || defined(INCLUDE_OrgJodaConvertFromString))
#define OrgJodaConvertFromString_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol OrgJodaConvertFromString < JavaLangAnnotationAnnotation >

@end

@interface OrgJodaConvertFromString : NSObject < OrgJodaConvertFromString >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaConvertFromString)

FOUNDATION_EXPORT id<OrgJodaConvertFromString> create_OrgJodaConvertFromString();

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertFromString)

#endif

#pragma pop_macro("INCLUDE_ALL_FromString")
