//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/JDKStringConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JDKStringConverter")
#ifdef RESTRICT_JDKStringConverter
#define INCLUDE_ALL_JDKStringConverter 0
#else
#define INCLUDE_ALL_JDKStringConverter 1
#endif
#undef RESTRICT_JDKStringConverter

#if !defined (OrgJodaConvertJDKStringConverter_) && (INCLUDE_ALL_JDKStringConverter || defined(INCLUDE_OrgJodaConvertJDKStringConverter))
#define OrgJodaConvertJDKStringConverter_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_TypedStringConverter 1
#define INCLUDE_OrgJodaConvertTypedStringConverter 1
#include "TypedStringConverter.h"

@class IOSClass;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, OrgJodaConvertJDKStringConverter_Enum) {
  OrgJodaConvertJDKStringConverter_Enum_STRING = 0,
  OrgJodaConvertJDKStringConverter_Enum_CHAR_SEQUENCE = 1,
  OrgJodaConvertJDKStringConverter_Enum_STRING_BUFFER = 2,
  OrgJodaConvertJDKStringConverter_Enum_STRING_BUILDER = 3,
  OrgJodaConvertJDKStringConverter_Enum_LONG = 4,
  OrgJodaConvertJDKStringConverter_Enum_INTEGER = 5,
  OrgJodaConvertJDKStringConverter_Enum_SHORT = 6,
  OrgJodaConvertJDKStringConverter_Enum_BYTE = 7,
  OrgJodaConvertJDKStringConverter_Enum_BYTE_ARRAY = 8,
  OrgJodaConvertJDKStringConverter_Enum_CHARACTER = 9,
  OrgJodaConvertJDKStringConverter_Enum_CHAR_ARRAY = 10,
  OrgJodaConvertJDKStringConverter_Enum_BOOLEAN = 11,
  OrgJodaConvertJDKStringConverter_Enum_DOUBLE = 12,
  OrgJodaConvertJDKStringConverter_Enum_FLOAT = 13,
  OrgJodaConvertJDKStringConverter_Enum_BIG_INTEGER = 14,
  OrgJodaConvertJDKStringConverter_Enum_BIG_DECIMAL = 15,
  OrgJodaConvertJDKStringConverter_Enum_ATOMIC_LONG = 16,
  OrgJodaConvertJDKStringConverter_Enum_ATOMIC_INTEGER = 17,
  OrgJodaConvertJDKStringConverter_Enum_ATOMIC_BOOLEAN = 18,
  OrgJodaConvertJDKStringConverter_Enum_LOCALE = 19,
  OrgJodaConvertJDKStringConverter_Enum_CLASS = 20,
  OrgJodaConvertJDKStringConverter_Enum_PACKAGE = 21,
  OrgJodaConvertJDKStringConverter_Enum_CURRENCY = 22,
  OrgJodaConvertJDKStringConverter_Enum_TIME_ZONE = 23,
  OrgJodaConvertJDKStringConverter_Enum_UUID = 24,
  OrgJodaConvertJDKStringConverter_Enum_URL = 25,
  OrgJodaConvertJDKStringConverter_Enum_URI = 26,
  OrgJodaConvertJDKStringConverter_Enum_INET_ADDRESS = 27,
  OrgJodaConvertJDKStringConverter_Enum_FILE = 28,
  OrgJodaConvertJDKStringConverter_Enum_DATE = 29,
  OrgJodaConvertJDKStringConverter_Enum_CALENDAR = 30,
};

@interface OrgJodaConvertJDKStringConverter : JavaLangEnum < NSCopying, OrgJodaConvertTypedStringConverter >

#pragma mark Public

- (NSString *)convertToStringWithId:(id)object;

- (IOSClass *)getEffectiveType;

+ (OrgJodaConvertJDKStringConverter *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (IOSClass *)getType;

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(OrgJodaConvertJDKStringConverter)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_values_[];

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_STRING();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, STRING)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_CHAR_SEQUENCE();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, CHAR_SEQUENCE)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_STRING_BUFFER();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, STRING_BUFFER)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_STRING_BUILDER();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, STRING_BUILDER)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_LONG();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, LONG)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_INTEGER();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, INTEGER)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_SHORT();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, SHORT)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_BYTE();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, BYTE)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_BYTE_ARRAY();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, BYTE_ARRAY)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_CHARACTER();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, CHARACTER)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_CHAR_ARRAY();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, CHAR_ARRAY)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_BOOLEAN();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, BOOLEAN)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_DOUBLE();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, DOUBLE)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_FLOAT();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, FLOAT)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_BIG_INTEGER();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, BIG_INTEGER)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_BIG_DECIMAL();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, BIG_DECIMAL)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_ATOMIC_LONG();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, ATOMIC_LONG)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_ATOMIC_INTEGER();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, ATOMIC_INTEGER)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_ATOMIC_BOOLEAN();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, ATOMIC_BOOLEAN)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_LOCALE();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, LOCALE)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_CLASS();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, CLASS)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_PACKAGE();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, PACKAGE)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_CURRENCY();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, CURRENCY)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_TIME_ZONE();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, TIME_ZONE)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_UUID();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, UUID)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_URL();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, URL)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_URI();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, URI)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_INET_ADDRESS();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, INET_ADDRESS)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_FILE();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, FILE)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_DATE();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, DATE)

inline OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_get_CALENDAR();
J2OBJC_ENUM_CONSTANT(OrgJodaConvertJDKStringConverter, CALENDAR)

FOUNDATION_EXPORT IOSObjectArray *OrgJodaConvertJDKStringConverter_values();

FOUNDATION_EXPORT OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgJodaConvertJDKStringConverter *OrgJodaConvertJDKStringConverter_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertJDKStringConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_JDKStringConverter")
