//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/ReflectionStringConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ReflectionStringConverter")
#ifdef RESTRICT_ReflectionStringConverter
#define INCLUDE_ALL_ReflectionStringConverter 0
#else
#define INCLUDE_ALL_ReflectionStringConverter 1
#endif
#undef RESTRICT_ReflectionStringConverter

#if !defined (OrgJodaConvertReflectionStringConverter_) && (INCLUDE_ALL_ReflectionStringConverter || defined(INCLUDE_OrgJodaConvertReflectionStringConverter))
#define OrgJodaConvertReflectionStringConverter_

#define RESTRICT_TypedStringConverter 1
#define INCLUDE_OrgJodaConvertTypedStringConverter 1
#include "TypedStringConverter.h"

@class IOSClass;
@class JavaLangReflectMethod;

@interface OrgJodaConvertReflectionStringConverter : NSObject < OrgJodaConvertTypedStringConverter >

#pragma mark Public

- (NSString *)convertToStringWithId:(id)object;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithIOSClass:(IOSClass *)cls
       withJavaLangReflectMethod:(JavaLangReflectMethod *)toString;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaConvertReflectionStringConverter)

FOUNDATION_EXPORT void OrgJodaConvertReflectionStringConverter_initWithIOSClass_withJavaLangReflectMethod_(OrgJodaConvertReflectionStringConverter *self, IOSClass *cls, JavaLangReflectMethod *toString);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertReflectionStringConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_ReflectionStringConverter")
