//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/RenameHandler.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RenameHandler")
#ifdef RESTRICT_RenameHandler
#define INCLUDE_ALL_RenameHandler 0
#else
#define INCLUDE_ALL_RenameHandler 1
#endif
#undef RESTRICT_RenameHandler

#if !defined (OrgJodaConvertRenameHandler_) && (INCLUDE_ALL_RenameHandler || defined(INCLUDE_OrgJodaConvertRenameHandler))
#define OrgJodaConvertRenameHandler_

@class IOSClass;
@class JavaLangEnum;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

@interface OrgJodaConvertRenameHandler : NSObject

#pragma mark Public

+ (OrgJodaConvertRenameHandler *)create;

- (id<JavaUtilMap>)getEnumRenamesWithIOSClass:(IOSClass *)type;

- (id<JavaUtilSet>)getEnumTypesWithRenames;

- (id<JavaUtilMap>)getTypeRenames;

- (JavaLangEnum *)lookupEnumWithIOSClass:(IOSClass *)type
                            withNSString:(NSString *)name;

- (IOSClass *)lookupTypeWithNSString:(NSString *)name;

- (void)renamedEnumWithNSString:(NSString *)oldName
               withJavaLangEnum:(JavaLangEnum *)currentValue;

- (void)renamedTypeWithNSString:(NSString *)oldName
                   withIOSClass:(IOSClass *)currentValue;

- (NSString *)description;

#pragma mark Package-Private

- (IOSClass *)loadTypeWithNSString:(NSString *)fullName;

@end

J2OBJC_STATIC_INIT(OrgJodaConvertRenameHandler)

inline OrgJodaConvertRenameHandler *OrgJodaConvertRenameHandler_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJodaConvertRenameHandler *OrgJodaConvertRenameHandler_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJodaConvertRenameHandler, INSTANCE, OrgJodaConvertRenameHandler *)

FOUNDATION_EXPORT OrgJodaConvertRenameHandler *OrgJodaConvertRenameHandler_create();

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertRenameHandler)

#endif

#pragma pop_macro("INCLUDE_ALL_RenameHandler")
