//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/StringConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_StringConverter")
#ifdef RESTRICT_StringConverter
#define INCLUDE_ALL_StringConverter 0
#else
#define INCLUDE_ALL_StringConverter 1
#endif
#undef RESTRICT_StringConverter

#if !defined (OrgJodaConvertStringConverter_) && (INCLUDE_ALL_StringConverter || defined(INCLUDE_OrgJodaConvertStringConverter))
#define OrgJodaConvertStringConverter_

#define RESTRICT_ToStringConverter 1
#define INCLUDE_OrgJodaConvertToStringConverter 1
#include "ToStringConverter.h"

#define RESTRICT_FromStringConverter 1
#define INCLUDE_OrgJodaConvertFromStringConverter 1
#include "FromStringConverter.h"

@protocol OrgJodaConvertStringConverter < OrgJodaConvertToStringConverter, OrgJodaConvertFromStringConverter, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaConvertStringConverter)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertStringConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_StringConverter")
