//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/StringConverter.java
//

#include "J2ObjC_source.h"
#include "StringConverter.h"

@interface OrgJodaConvertStringConverter : NSObject

@end

@implementation OrgJodaConvertStringConverter

+ (const J2ObjcClassInfo *)__metadata {
  static const void *ptrTable[] = { "<T:Ljava/lang/Object;>Ljava/lang/Object;Lorg/joda/convert/ToStringConverter<TT;>;Lorg/joda/convert/FromStringConverter<TT;>;" };
  static const J2ObjcClassInfo _OrgJodaConvertStringConverter = { "StringConverter", "org.joda.convert", ptrTable, NULL, NULL, 7, 0x609, 0, 0, -1, -1, -1, 0, -1 };
  return &_OrgJodaConvertStringConverter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJodaConvertStringConverter)
