//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/ToStringConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ToStringConverter")
#ifdef RESTRICT_ToStringConverter
#define INCLUDE_ALL_ToStringConverter 0
#else
#define INCLUDE_ALL_ToStringConverter 1
#endif
#undef RESTRICT_ToStringConverter

#if !defined (OrgJodaConvertToStringConverter_) && (INCLUDE_ALL_ToStringConverter || defined(INCLUDE_OrgJodaConvertToStringConverter))
#define OrgJodaConvertToStringConverter_

@protocol OrgJodaConvertToStringConverter < JavaObject >

- (NSString *)convertToStringWithId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaConvertToStringConverter)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertToStringConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_ToStringConverter")
