//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/ToString.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ToString")
#ifdef RESTRICT_ToString
#define INCLUDE_ALL_ToString 0
#else
#define INCLUDE_ALL_ToString 1
#endif
#undef RESTRICT_ToString

#if !defined (OrgJodaConvertToString_) && (INCLUDE_ALL_ToString || defined(INCLUDE_OrgJodaConvertToString))
#define OrgJodaConvertToString_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol OrgJodaConvertToString < JavaLangAnnotationAnnotation >

@end

@interface OrgJodaConvertToString : NSObject < OrgJodaConvertToString >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaConvertToString)

FOUNDATION_EXPORT id<OrgJodaConvertToString> create_OrgJodaConvertToString();

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertToString)

#endif

#pragma pop_macro("INCLUDE_ALL_ToString")
