//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/ToStringConverter.java
//

#include "J2ObjC_source.h"
#include "ToStringConverter.h"

@interface OrgJodaConvertToStringConverter : NSObject

@end

@implementation OrgJodaConvertToStringConverter

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, 0, 1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(convertToStringWithId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "convertToString", "LNSObject;", "(TT;)Ljava/lang/String;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _OrgJodaConvertToStringConverter = { "ToStringConverter", "org.joda.convert", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, 3, -1 };
  return &_OrgJodaConvertToStringConverter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJodaConvertToStringConverter)
