//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/TypedStringConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TypedStringConverter")
#ifdef RESTRICT_TypedStringConverter
#define INCLUDE_ALL_TypedStringConverter 0
#else
#define INCLUDE_ALL_TypedStringConverter 1
#endif
#undef RESTRICT_TypedStringConverter

#if !defined (OrgJodaConvertTypedStringConverter_) && (INCLUDE_ALL_TypedStringConverter || defined(INCLUDE_OrgJodaConvertTypedStringConverter))
#define OrgJodaConvertTypedStringConverter_

#define RESTRICT_StringConverter 1
#define INCLUDE_OrgJodaConvertStringConverter 1
#include "StringConverter.h"

@class IOSClass;

@protocol OrgJodaConvertTypedStringConverter < OrgJodaConvertStringConverter, JavaObject >

- (IOSClass *)getEffectiveType;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaConvertTypedStringConverter)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertTypedStringConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_TypedStringConverter")
