//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/TypedStringConverter.java
//

#include "J2ObjC_source.h"
#include "TypedStringConverter.h"

@interface OrgJodaConvertTypedStringConverter : NSObject

@end

@implementation OrgJodaConvertTypedStringConverter

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LIOSClass;", 0x401, -1, -1, -1, 0, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getEffectiveType);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "()Ljava/lang/Class<*>;", "<T:Ljava/lang/Object;>Ljava/lang/Object;Lorg/joda/convert/StringConverter<TT;>;" };
  static const J2ObjcClassInfo _OrgJodaConvertTypedStringConverter = { "TypedStringConverter", "org.joda.convert", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, 1, -1 };
  return &_OrgJodaConvertTypedStringConverter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJodaConvertTypedStringConverter)
