//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/joda-convert/build/mainTranslationExtraction/org/joda/convert/TypedAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TypedAdapter")
#ifdef RESTRICT_TypedAdapter
#define INCLUDE_ALL_TypedAdapter 0
#else
#define INCLUDE_ALL_TypedAdapter 1
#endif
#undef RESTRICT_TypedAdapter

#if !defined (OrgJodaConvertTypedAdapter_) && (INCLUDE_ALL_TypedAdapter || defined(INCLUDE_OrgJodaConvertTypedAdapter))
#define OrgJodaConvertTypedAdapter_

#define RESTRICT_TypedStringConverter 1
#define INCLUDE_OrgJodaConvertTypedStringConverter 1
#include "TypedStringConverter.h"

@class IOSClass;
@protocol OrgJodaConvertStringConverter;

@interface OrgJodaConvertTypedAdapter : NSObject < OrgJodaConvertTypedStringConverter >

#pragma mark Public

- (id)convertFromStringWithIOSClass:(IOSClass *)cls
                       withNSString:(NSString *)str;

- (NSString *)convertToStringWithId:(id)object;

- (IOSClass *)getEffectiveType;

- (NSString *)description;

#pragma mark Package-Private

+ (id<OrgJodaConvertTypedStringConverter>)adaptWithIOSClass:(IOSClass *)cls
                          withOrgJodaConvertStringConverter:(id<OrgJodaConvertStringConverter>)converter;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaConvertTypedAdapter)

FOUNDATION_EXPORT id<OrgJodaConvertTypedStringConverter> OrgJodaConvertTypedAdapter_adaptWithIOSClass_withOrgJodaConvertStringConverter_(IOSClass *cls, id<OrgJodaConvertStringConverter> converter);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaConvertTypedAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_TypedAdapter")
